### ISSUE TITLE
PHP compatibility

### ISSUE THREAD

**Issue by danny-balance** [DanielSousa/rebuild-urlrewrite#1]
Is there a specific reason this module requires PHP 7+?

```json
"require": {
    "php": "~7.0.0"
},
```

It would be great to be able to install on PHP 5.6 _(I'm having issues with my current installation + PHP 7, but that's beside the point)_.

Magento 2.1.2+ itself [can run](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html) on PHP 5.6.5+.

**Comment by DanielSousa** [comment]
Hi @danny-balance,

I didn't made any tests on 5.6.

**Comment by DanielSousa** [comment]
I just release version 1.1.0.
You can use this version.
